### ISSUE TITLE
images issues

### ISSUE THREAD

**Issue by treasuretron** [Zedelghem/pystatic#13]
firstly, markdown image embeds don't seem to be working but maybe that's fine, html `<img>` tag works. But relative links only work either in the post view or in the index, but not both.

If I include `<img src=../assets/image.jpg>` in a .md post, that image will show in the posts/blogpost.html but in the index it shows as not working since from where the index is it should link to `<img src=assets/image.jpg>` instead.

A solution is obviously to use hardlinks but would be cool for relative links to be parsed and rendered right in both places.

Or perhaps I'm doing something wrong! ;)

**Comment by Zedelghem** [comment]
I need more info because the image embed works for me. 

1. Are you sure you've got the parentheses right? E.g.:
`![](https://i.pinimg.com/originals/a7/71/26/a77126ed93bff8d24aaa4aa44c77a9b8.jpg)`

2. Check your PyPI markdown version, I use 3.1 and it is recommended because of the footnotes.

PS: Relative links for image embed seem to work for me as well. Provided you keep the images in the assets folder, the correct structure of the link would be as follows:
`![](../assets/image.jpg)`

**Comment by treasuretron** [comment]
huh, well, seems I can't reproduce my own bug! I think I wasn't giving the path in the form `../asstes/image.jpg`. Or perhaps I was using wrong md syntax, I am new to markdown. Thanks!
